language: python

python:
  - "3.6"

install:
  - git clone https://github.com/chris104957/helloworld.git
  - cd helloworld
  - pip install twine

deploy:
  provider: pypi
#  user: "christopherdavies553@gmail.com"
#  password: "C#d14095"
#  server: https://api.python-private-package-index.com/63cdQSDO/


