language: python

python:
  - "3.6"

install:
  - git clone https://github.com/chris104957/helloworld.git
  - cd helloworld
  - pip install twine
  - python setup.py sdist

script:
  - twine upload dist/*




