language: python

python:
  - "3.6"

install:
  - pip install twine
  - python setup.py sdist

deploy:
  - twine upload --repository-url https://api.python-private-package-index.com/63cdQSDO/ dist/*


